# Generated by Django 4.2 on 2023-04-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "G Option"),
                    ("PG", "Pg Option"),
                    ("PG-13", "Pg 13 Option"),
                    ("R", "R Option"),
                    ("NC-17", "Nc 17 Option"),
                ],
                default="G",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(default=None, null=True),
        ),
    ]
